### ISSUE TITLE
Circle function is cut off at the bottom

### ISSUE THREAD

**Issue by DrBabbage** [WebSVG/voronoi#32]
Thank you for this awesome tool.
The bottom of the circle tool is cut off :/ This happens on both websites. Also gets into svg export. Tried different browsers. Issue persists.

![image](https://user-images.githubusercontent.com/66676158/227809126-b950e924-275d-4857-ad5b-6ae927fefa76.png)

**Comment by wassfila** [comment]
Hi and thank you for the feedback about this tool.

You can fix this by increasing the size of the SVG. It is unfortunately manual, but you can freely adjust the width and the height here 
<img width="120" alt="image" src="https://user-images.githubusercontent.com/1510763/228016640-bd09de2b-035f-457a-b255-417d394597cd.png">
